"""Initial migration

Revision ID: fb893c4bba61
Revises: 
Create Date: 2026-08-22 05:36:20.937349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'fb893c4bba61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def get_json_type():
    """Get appropriate JSON type for the current dialect."""
    from alembic import op
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        return postgresql.JSONB(astext_type=Text())
    else:
        # SQLite doesn't support JSONB, use JSON instead
        return sa.JSON()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    json_type = get_json_type()
    
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.Enum('LSTM', 'HYBRID', 'ARIMA', 'ENSEMBLE', name='modeltype'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('training_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('feature_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_registry'))
    )
    op.create_index('ix_model_registry_created_at', 'model_registry', ['created_at'], unique=False)
    op.create_index('ix_model_registry_model_type', 'model_registry', ['model_type'], unique=False)
    op.create_index(op.f('ix_model_registry_name'), 'model_registry', ['name'], unique=True)
    op.create_index('ix_model_registry_tags', 'model_registry', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('old_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('date_column', sa.String(length=100), nullable=False),
    sa.Column('sales_column', sa.String(length=100), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_datasets_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index('ix_datasets_created_at', 'datasets', ['created_at'], unique=False)
    op.create_index('ix_datasets_name', 'datasets', ['name'], unique=False)
    op.create_index('ix_datasets_owner_id', 'datasets', ['owner_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mape', sa.Float(), nullable=False),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('test_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False),
    sa.Column('additional_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], name=op.f('fk_model_metrics_model_id_model_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_metrics')),
    sa.UniqueConstraint('model_id', 'model_version', name='uq_model_metrics_version')
    )
    op.create_index('ix_model_metrics_evaluated_at', 'model_metrics', ['evaluated_at'], unique=False)
    op.create_index('ix_model_metrics_model_id', 'model_metrics', ['model_id'], unique=False)
    op.create_index('ix_model_metrics_model_version', 'model_metrics', ['model_id', 'model_version'], unique=False)
    op.create_table('forecasting_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Enum('train', 'forecast', 'train_all', name='job_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('seq_length', sa.Integer(), nullable=False),
    sa.Column('lstm_epochs', sa.Integer(), nullable=False),
    sa.Column('lstm_batch_size', sa.Integer(), nullable=False),
    sa.Column('arima_order', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('forecast_steps', sa.Integer(), nullable=False),
    sa.Column('test_size', sa.Float(), nullable=False),
    sa.Column('lstm_model_path', sa.String(length=512), nullable=True),
    sa.Column('hybrid_model_path', sa.String(length=512), nullable=True),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('lstm_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('hybrid_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('best_model', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_forecasting_jobs_dataset_id_datasets')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_forecasting_jobs_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasting_jobs'))
    )
    op.create_index('ix_forecasting_jobs_created_at', 'forecasting_jobs', ['created_at'], unique=False)
    op.create_index('ix_forecasting_jobs_dataset_id', 'forecasting_jobs', ['dataset_id'], unique=False)
    op.create_index('ix_forecasting_jobs_owner_id', 'forecasting_jobs', ['owner_id'], unique=False)
    op.create_index('ix_forecasting_jobs_status', 'forecasting_jobs', ['status'], unique=False)
    op.create_index('ix_forecasting_jobs_status_created', 'forecasting_jobs', ['status', 'created_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.Enum('LSTM', 'HYBRID', 'ARIMA', 'ENSEMBLE', name='modeltype'), nullable=False),
    sa.Column('forecast_steps', sa.Integer(), nullable=False),
    sa.Column('forecast_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('forecast_dates', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('forecast_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['forecasting_jobs.id'], name=op.f('fk_forecasts_job_id_forecasting_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts'))
    )
    op.create_index('ix_forecasts_created_at', 'forecasts', ['created_at'], unique=False)
    op.create_index('ix_forecasts_job_id', 'forecasts', ['job_id'], unique=False)
    op.create_index('ix_forecasts_model_type', 'forecasts', ['model_type'], unique=False)
    op.create_table('inventory_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=True),
    sa.Column('service_level', sa.Float(), nullable=False),
    sa.Column('lead_time', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('annual_demand', sa.Float(), nullable=True),
    sa.Column('holding_cost', sa.Float(), nullable=True),
    sa.Column('ordering_cost', sa.Float(), nullable=True),
    sa.Column('forecast_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('average_daily_demand', sa.Float(), nullable=False),
    sa.Column('demand_std_dev', sa.Float(), nullable=False),
    sa.Column('lead_time_demand', sa.Float(), nullable=False),
    sa.Column('safety_stock_basis', sa.String(length=50), nullable=False),
    sa.Column('economic_order_quantity', sa.Float(), nullable=True),
    sa.Column('stockout_risk', sa.Float(), nullable=True),
    sa.Column('overstock_risk', sa.Float(), nullable=True),
    sa.Column('projection', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], name=op.f('fk_inventory_analysis_forecast_id_forecasts')),
    sa.ForeignKeyConstraint(['job_id'], ['forecasting_jobs.id'], name=op.f('fk_inventory_analysis_job_id_forecasting_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_analysis'))
    )
    op.create_index('ix_inventory_analysis_created_at', 'inventory_analysis', ['created_at'], unique=False)
    op.create_index('ix_inventory_analysis_job_id', 'inventory_analysis', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_analysis_job_id', table_name='inventory_analysis')
    op.drop_index('ix_inventory_analysis_created_at', table_name='inventory_analysis')
    op.drop_table('inventory_analysis')
    op.drop_index('ix_forecasts_model_type', table_name='forecasts')
    op.drop_index('ix_forecasts_job_id', table_name='forecasts')
    op.drop_index('ix_forecasts_created_at', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_forecasting_jobs_status_created', table_name='forecasting_jobs')
    op.drop_index('ix_forecasting_jobs_status', table_name='forecasting_jobs')
    op.drop_index('ix_forecasting_jobs_owner_id', table_name='forecasting_jobs')
    op.drop_index('ix_forecasting_jobs_dataset_id', table_name='forecasting_jobs')
    op.drop_index('ix_forecasting_jobs_created_at', table_name='forecasting_jobs')
    op.drop_table('forecasting_jobs')
    op.drop_index('ix_model_metrics_model_version', table_name='model_metrics')
    op.drop_index('ix_model_metrics_model_id', table_name='model_metrics')
    op.drop_index('ix_model_metrics_evaluated_at', table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index('ix_datasets_owner_id', table_name='datasets')
    op.drop_index('ix_datasets_name', table_name='datasets')
    op.drop_index('ix_datasets_created_at', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_model_registry_tags', table_name='model_registry', postgresql_using='gin')
    op.drop_index(op.f('ix_model_registry_name'), table_name='model_registry')
    op.drop_index('ix_model_registry_model_type', table_name='model_registry')
    op.drop_index('ix_model_registry_created_at', table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###